#!/bin/bash
# NAME:      90-updates-available-no-esm
#
# DESCRIPTION: This is a replacement for 90-updates-available
#
#              Do to the ANNOYING spam that ESM injects into this file.
#              This will simply grep the important parts from the file.
#
#
# AUTHOR     : Richard J. DURSO
# DATE       : 06/29/2025
# VERSION    : 1.0.2
##############################################################################

stamp="/var/lib/update-notifier/updates-available"

if [ -r "$stamp" ]; then
	echo -e "\nUpdates:"
	grep --color=never -E '^[0-9]* update|--upgradable' "$stamp"
fi

find $stamp -newermt 'now-7 days' 2> /dev/null | grep -q -m 1 '.' || /usr/share/update-notifier/notify-updates-outdated
